# Generated by Django 4.2.6 on 2023-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
