# Generated by Django 4.2.6 on 2023-10-06 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_post_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
    ]
